### ISSUE TITLE
Support scripts attached after window 'load' event

### ISSUE THREAD

**Issue by erykpiast** [mvc-works/webpack-hud#1]
Because of `tipElement` is attached to document on window `load` event, messages are not visible when bundle is loaded dynamically (non-blocking way). I'll make PR for this.

**Comment by jiyinyiyong** [comment]
Merged and `0.0.7` is released.

I also modified `publish` field in `package.json` which tried to add `lib/` in git. Did you generate `package.json` from some tools, it looks quite long too me? I never used so many features in npm scripts since I prefer gulp.

**Comment by erykpiast** [comment]
Nope, it's hand-crafted. For not complicated building process I prefer pure NPM scripts.It's just a matter of preference :)
