### ISSUE TITLE
ie11 support

### ISSUE THREAD

**Issue by FredericHeem** [mvc-works/webpack-hud#4]
Dear,
On IE11, an exception occurs inside the `diffhtml` library, at `render.js` line 72:
```
element.dispatchEvent(new CustomEvent('renderComplete'));
```
Exception: `Object doesn't support this action`

Thanks a lot for this awesome project.

**Comment by jiyinyiyong** [comment]
no longer diffhtml, I think, it's already updated https://github.com/mvc-works/bottom-tip/blob/master/package.json#L27

**Comment by FredericHeem** [comment]
Sorry for the noise, updating to version 0.0.9 just makes the issue disappear. Thanks a lot.
